name: dart_api
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
environment:
  sdk: ^3.3.1

# Add regular dependencies here.
dependencies:
  hive: ^2.2.3
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  shelf: ^1.4.1
  shelf_router: ^1.1.4
# path: ^1.8.0
dev_dependencies:
  build_runner: ^2.4.9
  hive_generator: ^2.0.1
  lints: ^3.0.0
  shelf_router_generator: ^1.1.0
  test: ^1.24.0
